### ISSUE TITLE
Resolve warnings pointed out by dart analyzer

### ISSUE THREAD

**Issue by noriHanda** [marcglasberg/fast_immutable_collections#49]
## Issue

Warnings are shown on pub.dev and points on this package are reduced because some easy-to-fix problems are yet to be fixed.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/18581236/223617390-6581893b-cd2c-4d1a-ba98-ff216f9f3dab.png">

Resolving these problems would raise the score and fame of this package as deserved.

**Comment by RandalSchwartz** [comment]
I'm a bit concerned that this is the tip of the iceberg, seeing this:

```yaml
include: package:lint/analysis_options.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    prefer_double_quotes: false
    no_leading_underscores_for_local_identifiers: false
    no_runtimeType_toString: false
    avoid_multiple_declarations_per_line: false
    parameter_assignments: false
    avoid_dynamic_calls: false
    avoid_redundant_argument_values: false
    avoid_print: false
    always_use_package_imports: false
    avoid_positional_boolean_parameters: false
    prefer_const_literals_to_create_immutables: false
    prefer_interpolation_to_compose_strings: false
    avoid_function_literals_in_foreach_calls: false
    cast_nullable_to_non_nullable: false
    require_trailing_commas: false
    join_return_with_assignment: false
    unnecessary_parenthesis: false
    use_is_even_rather_than_modulo: false
    use_string_buffers: false
```

I'd strongly recommend looking at package:very_good_analysis, and turn off nothing, and see how close one can get to superclean.
